.SUFFIXES: .tex .pdf

.tex.pdf: $<.tex
	@ pdflatex -synctex=1 $<
	@ bibtex ${<:.tex=.aux}
	@ pdflatex -synctex=1 $<
	@ pdflatex -synctex=1 $<

EMBED_OPTS := -dPDFSETTINGS=/prepress -dSubsetFonts=true -dEmbedAllFonts=true -dMaxSubsetPct=100 -dCompatibilityLevel=1.3
# These are options to make 'ps2pdf' embed all fonts.
